#ifndef FILES_H
#define FILES_H


#include <stdarg.h>
#include "defines_config.h"

typedef struct {
    char name[LINE_SIZE];                               // For identification
    char contents[MAX_FILE_LENGTH][MAX_FILE_WIDTH];     // For data storage
    int line;
    int position;
    int length;
    } sfile;


sfile files[MAX_FILES] = {
    {.name = "preferences.txt",
        .contents = {
        "CiancioTest11.asm\n",
        "01\n",
        "0\n"
        },
        .length = 3,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest10.asm",
        .contents = {
        "; Program for linked lists by Seth Ciancio\n",
        "; Fills linked list to a certain number of items (entered by user), and then prints it back.\n",
        "; Get desired length of list\n",
        "get\n",
        "mov [MV] ax\n",
        "; Create and print list\n",
        "fun [CL] 2 [LS] [MV]\n",
        "fun [PL] 1 [LS]\n",
        "halt\n",
        "; Main variable - variable for the starting bit of code\n",
        "MV\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "; Createlist parameter\n",
        "CP\n",
        "\n",
        "; Createlist. Takes a location to put the list and a desired length\n",
        "CL\n",
        "mov bx [CP]\n",
        "mov bx [bx+2]\n",
        "mov cx [bx]\n",
        "mov bx [CP]\n",
        "mov bx [bx+1]\n",
        "mov dx bx\n",
        "; CreateListLoop start\n",
        "CS\n",
        "cmp cx 0\n",
        "jbe [CE]\n",
        "; Move BX to the next item in the list\n",
        "mov bx dx\n",
        "get\n",
        "; I'm adding three instead of two just so there's a gap between...\n",
        "add dx 3\n",
        "; Put the address of the next list item & the value into the list\n",
        "mov [bx] dx\n",
        "mov [bx+1] ax\n",
        "add cx -1\n",
        "jmp [CS]\n",
        "; Createlist end\n",
        "CE\n",
        "; So we know the list is over.\n",
        "mov ax -1\n",
        "mov [bx] ax4\n",
        "ret\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "; Printlist parameter\n",
        "PP\n",
        "\n",
        "; Print List function. Takes the start of the list\n",
        "PL\n",
        "mov bx [PP]\n",
        "mov bx [bx+1]\n",
        "; For finding the end of the list later\n",
        "mov cx -1\n",
        "; Printlistloop Start\n",
        "PS\n",
        "mov ax [bx+1]\n",
        "put\n",
        "; Check if the list is over\n",
        "cmp cx [bx]\n",
        "mov bx [bx]\n",
        "jne [PS]\n",
        "ret\n",
        "\n",
        "\n",
        "\n",
        "; List start\n",
        "LS",
        },
        .length = 73,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest11.asm",
        .contents = {
        "; Program to take values and then print them backwards (testing recursive functions)\n",
        "; Get the number of values to enter.\n",
        "get\n",
        "; Check size (for memory safety!)\n",
        "cmp ax 18\n",
        "ja [EH]\n",
        "mov [MV] ax\n",
        "; Get & print all values\n",
        "fun [FN] 1 [MV]\n",
        "; Put the number of values, just so the lists are perfect opposite.\n",
        "put\n",
        "; Early Halt (for memory safety)\n",
        "EH\n",
        "halt\n",
        "; Main ( like main() function ) variable\n",
        "MV\n",
        "\n",
        "\n",
        "; Function parameter\n",
        "FP\n",
        "\n",
        "; Function\n",
        "FN\n",
        "; get the pointer to the pointer to the value we want.\n",
        "mov bx [FP]\n",
        "; get the pointer to the value we want\n",
        "mov bx [bx+1]\n",
        "; get the value we want (the counter)\n",
        "mov cx [bx]\n",
        "get\n",
        "; DEC counter\n",
        "add cx -1\n",
        "; Store counter to pass forward\n",
        "mov [VR] cx\n",
        "cmp cx 0\n",
        "JBE [EN]\n",
        "fun [FN] 1 [VR]\n",
        "; END (of function)\n",
        "EN\n",
        "put\n",
        "ret\n",
        "\n",
        "; Variable for storage of the counter between functions\n",
        "VR",
        },
        .length = 44,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest4.asm",
        .contents = {
        "mov ax [VL]\n",
        "mov bx [VK]\n",
        "add ax bx\n",
        "mov [VJ] ax\n",
        "put\n",
        "halt\n",
        "\n",
        "VL\n",
        "30\n",
        "VK\n",
        "25\n",
        "VJ\n",
        },
        .length = 12,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest5.asm",
        .contents = {
        "mov cx 20\n",
        "mov [100] cx\n",
        "mov dx 0\n",
        "mov [101] dx\n",
        "mov bx [100]\n",
        "add bx [101]\n",
        "mov [102] bx\n",
        "mov ax bx\n",
        "mov ax 0\n",
        "put\n",
        "add ax 1\n",
        "cmp ax cx\n",
        "jbe [17]\n",
        "add ax -1\n",
        "cmp ax dx\n",
        "put\n",
        "ja [23]\n",
        "add ax -5\n",
        "cmp ax -15\n",
        "put\n",
        "jae [29]\n",
        "cmp ax -20\n",
        "jne [18]\n",
        "mov bx 20\n",
        "cmp ax bx\n",
        "jb [47]\n",
        "mov bx 1000\n",
        "add ax bx\n",
        "cmp ax bx\n",
        "jb [47]\n",
        "cmp ax [100]\n",
        "je [57]\n",
        "mov ax 999\n",
        "jmp [61]\n",
        "mov dx 999\n",
        "halt",
        },
        .length = 36,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest6.asm",
        .contents = {
        "mov bx 10\n",
        "mov cx 0\n",
        "get\n",
        "add cx ax\n",
        "add bx -1\n",
        "cmp bx 0\n",
        "ja [4]\n",
        "mov [17] cx\n",
        "mov ax cx\n",
        "put\n",
        "halt",
        },
        .length = 11,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest7.asm",
        .contents = {
        "mov bx 10\n",
        "mov cx 0\n",
        "fun [FN] 2 0 100\n",
        "mov ax [9]\n",
        "add cx ax\n",
        "add bx -1\n",
        "cmp bx 0\n",
        "ja [4]\n",
        "mov ax cx\n",
        "put\n",
        "halt\n",
        "\n",
        "\n",
        "; Function param\n",
        "FP\n",
        "\n",
        "; Function. Takes range and loops through inputs until it gets value within range.\n",
        "FN\n",
        "; This function takes a number & a range. Returns number if it's within range\n",
        "mov bx [FP]\n",
        "mov cx [bx+1]\n",
        "mov dx [bx+2]\n",
        "; Get next\n",
        "GN\n",
        "get\n",
        "cmp ax cx\n",
        "jb [GN]\n",
        "cmp ax dx\n",
        "ja [GN]\n",
        "ret",
        },
        .length = 30,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest8.asm",
        .contents = {
        "mov dx 10\n",
        "mov cx 0\n",
        "fun [FN] 2 0 100\n",
        "mov bx [9]\n",
        "add cx [bx]\n",
        "add dx -1\n",
        "cmp dx 0\n",
        "ja [4]\n",
        "mov ax cx\n",
        "put\n",
        "halt\n",
        "\n",
        "\n",
        "; Function param\n",
        "FP\n",
        "\n",
        "; Function. Takes range and loops through inputs until it gets value within range.\n",
        "FN\n",
        "; This function takes a number & a range. Returns number if it's within range\n",
        "mov bx [FP]\n",
        "mov cx [bx+1]\n",
        "mov dx [bx+2]\n",
        "; Get next\n",
        "GN\n",
        "get\n",
        "cmp ax cx\n",
        "jb [GN]\n",
        "cmp ax dx\n",
        "ja [GN]\n",
        "mov [VR] ax\n",
        "mov ax 44\n",
        "ret\n",
        "\n",
        "; Location of variable to be returned.\n",
        "VR",
        },
        .length = 35,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest9.asm",
        .contents = {
        "; Program to create and sort an array.\n",
        "; Create array based on user input\n",
        "fun [CA] 2 [AS] 10\n",
        "; Sort array w/ bubble sort\n",
        "fun [SA] 2 [AS] 10\n",
        "; Print sorted array.\n",
        "fun [PA] 2 [AS] 10\n",
        "halt\n",
        "\n",
        "\n",
        ";CreateArray parameter\n",
        "CP\n",
        "\n",
        ";Create Array function, takes the location and size of the array\n",
        "CA\n",
        "; Get array size\n",
        "mov bx [CP]\n",
        "mov cx [bx+2]\n",
        "; Get array start location\n",
        "mov bx [bx+1]\n",
        "; Add to get array end location\n",
        "add cx bx\n",
        "; So we don't go overboard\n",
        "add cx -1\n",
        ";start of loop\n",
        "NI\n",
        "cmp bx cx\n",
        "ja [CE]\n",
        "get\n",
        "mov [bx] ax\n",
        "add bx 1\n",
        "jmp [NI]\n",
        "; CreateArray End\n",
        "CE\n",
        "ret\n",
        "\n",
        "\n",
        ";PrintArray parameter\n",
        "PP\n",
        "\n",
        ";Print Array function, takes the location and size of the array\n",
        "PA\n",
        "; Get array size\n",
        "mov bx [PP]\n",
        "mov cx [bx+2]\n",
        "; Get array start location\n",
        "mov bx [bx+1]\n",
        "; Get array end location\n",
        "add cx bx\n",
        "; So we don't go overboard\n",
        "add cx -1\n",
        ";start of loop\n",
        "NO\n",
        "cmp bx cx\n",
        "ja [PE]\n",
        "mov ax [bx]\n",
        "put\n",
        "add bx 1\n",
        "jmp [NO]\n",
        ";PrintArray End\n",
        "PE\n",
        "ret\n",
        "\n",
        "\n",
        "; SortArray parameter\n",
        "SP\n",
        "\n",
        "; SortArray function, takes the location and size of the array\n",
        "SA\n",
        "; Get parameters\n",
        "mov bx [SP]\n",
        "; Array size\n",
        "mov dx [bx+2]\n",
        "; Array start location\n",
        "mov bx [bx+1]\n",
        "; Offset the first add in the loop\n",
        "add bx -1\n",
        "; Array end location\n",
        "add dx bx\n",
        "; Reset sortVariable\n",
        "mov ax 0\n",
        "mov [SV] ax\n",
        "; Sort next (main loop)\n",
        "SN\n",
        "add bx 1\n",
        "; Check if we're at the end of the array\n",
        "cmp bx dx\n",
        "je [SE]\n",
        "; Get two items from array\n",
        "mov ax [bx]\n",
        "mov cx [bx+1]\n",
        "cmp ax cx\n",
        "; If first is smaller, go to the next one\n",
        "jbe [SN]\n",
        "; If A is bigger, swap the values.\n",
        "mov [bx+1] ax\n",
        "mov [bx] cx\n",
        "; Take note that we had to swap\n",
        "mov ax 1\n",
        "mov [SV] ax\n",
        "; Check the next one\n",
        "jmp [SN]\n",
        "; Sortloop End\n",
        "SE\n",
        "; Check if we had to swap anything\n",
        "mov ax 0\n",
        "cmp ax [SV]\n",
        "JNE [SA]\n",
        "ret\n",
        "; Sort(swap?) variable\n",
        "SV\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "; Array start\n",
        "AS\n",
        "13\n",
        "41\n",
        "22\n",
        "66\n",
        "22\n",
        "12\n",
        "66\n",
        "11\n",
        "4\n",
        "12",
        },
        .length = 136,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest9_NoLabels.asm",
        .contents = {
        "fun [22] 2 [119] 10\n",
        "fun [66] 2 [119] 10\n",
        "fun [44] 2 [119] 10\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "mov bx [21]\n",
        "mov cx [bx+2]\n",
        "mov bx [bx+1]\n",
        "add cx bx\n",
        "add cx -1\n",
        "cmp bx cx\n",
        "ja [40]\n",
        "get\n",
        "mov [bx] ax\n",
        "add bx 1\n",
        "jmp [31]\n",
        "ret\n",
        "\n",
        "\n",
        "\n",
        "mov bx [43]\n",
        "mov cx [bx+2]\n",
        "mov bx [bx+1]\n",
        "add cx bx\n",
        "add cx -1\n",
        "cmp bx cx\n",
        "ja [62]\n",
        "mov ax [bx]\n",
        "put\n",
        "add bx 1\n",
        "jmp [53]\n",
        "ret\n",
        "\n",
        "\n",
        "\n",
        "mov bx [65]\n",
        "mov dx [bx+2]\n",
        "mov bx [bx+1]\n",
        "add bx -1\n",
        "add dx bx\n",
        "mov ax 0\n",
        "mov [106] ax\n",
        "add bx 1\n",
        "cmp bx dx\n",
        "je [99]\n",
        "mov ax [bx]\n",
        "mov cx [bx+1]\n",
        "cmp ax cx\n",
        "jbe [79]\n",
        "mov [bx+1] ax\n",
        "mov [bx] cx\n",
        "mov ax 1\n",
        "mov [106] ax\n",
        "jmp [79]\n",
        "mov ax 0\n",
        "cmp ax [106]\n",
        "JNE [66]\n",
        "ret\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        },
        .length = 73,
        .position = 0,
        .line = 0
    },

    {.name = "CiancioTest9NL.asm",
        .contents = {
        "fun [22] 2 [119] 10\n",
        "fun [66] 2 [119] 10\n",
        "fun [44] 2 [119] 10\n",
        "halt\n",
        "\n",
        "\n",
        "\n",
        "mov bx [21]\n",
        "mov cx [bx+2]\n",
        "mov bx [bx+1]\n",
        "add cx bx\n",
        "add cx -1\n",
        "cmp bx cx\n",
        "ja [40]\n",
        "get\n",
        "mov [bx] ax\n",
        "add bx 1\n",
        "jmp [31]\n",
        "ret\n",
        "\n",
        "\n",
        "\n",
        "mov bx [43]\n",
        "mov cx [bx+2]\n",
        "mov bx [bx+1]\n",
        "add cx bx\n",
        "add cx -1\n",
        "cmp bx cx\n",
        "ja [62]\n",
        "mov ax [bx]\n",
        "put\n",
        "add bx 1\n",
        "jmp [53]\n",
        "ret\n",
        "\n",
        "\n",
        "\n",
        "mov bx [65]\n",
        "mov dx [bx+2]\n",
        "mov bx [bx+1]\n",
        "add bx -1\n",
        "add dx bx\n",
        "mov ax 0\n",
        "mov [106] ax\n",
        "add bx 1\n",
        "cmp bx dx\n",
        "je [99]\n",
        "mov ax [bx]\n",
        "mov cx [bx+1]\n",
        "cmp ax cx\n",
        "jbe [79]\n",
        "mov [bx+1] ax\n",
        "mov [bx] cx\n",
        "mov ax 1\n",
        "mov [106] ax\n",
        "jmp [79]\n",
        "mov ax 0\n",
        "cmp ax [106]\n",
        "JNE [66]\n",
        "ret\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "13\n",
        "41\n",
        "22\n",
        "66\n",
        "22\n",
        "12\n",
        "66\n",
        "11\n",
        "4\n",
        "12\n",
        },
        .length = 83,
        .position = 0,
        .line = 0
    },

    {.name = "TEST.asm",
        .contents = {
        "mov cx 0\n",
        "mov dx 0\n",
        "get\n",
        "add dx ax\n",
        "add cx 1\n",
        "cmp cx 10\n",
        "jb [4]\n",
        "mov [50] dx\n",
        "mov ax dx\n",
        "put\n",
        "halt",
        },
        .length = 11,
        .position = 0,
        .line = 0
    }
};

// Opens a simulated file (analogous to fopen)
void sopen(sfile** out, const char file_name[LINE_SIZE], char open_type[2]) {
    if (out == NULL) return;
    if (file_name[0] == '\0') {
        *out = NULL;
        return;
    }

    for (int i = 0; i < MAX_FILES; i++) {
        if (strcmp(files[i].name, file_name) == 0) {
            *out = &files[i];
            (*out)->line = 0;
            (*out)->position = 0;
            return;
        }
    }
    *out = NULL;
    return;
}

// Closes a simulated file (analogous to fclose)
void sclose(sfile* fin) {
    // We don't actually need to do anything.
    // Just for API Compatibility
}



// Read up to max-1 characters into output from fin, stop on '\n' (include it) or EOF.
// Returns output on success, NULL on EOF or error.
char* sgets(char* output, int max, sfile* fin) {
    if (output == NULL || max <= 0) return NULL;
    if (fin == NULL || fin->line >= fin->length) return NULL;

    // Cap max to internal line width
    if (max > MAX_FILE_WIDTH) max = MAX_FILE_WIDTH;

    int out_i = 0;         //  Character of the output string

    // While we can write at least one more char (reserve space for '\0')
    while (out_i < max - 1 && fin->line < fin->length) {
        char c = fin->contents[fin->line][fin->position];
        output[out_i] = c;
        
        // We have to keep track of our position within the sfile & in the output string seperately
        out_i++;            //  Character of the output string
        fin->position++;    //  Character of one line of the sfile

        // If we read newline or nul, move to next stored row and stop
        if (c == '\n' || c == '\0') {
            // move to next stored row for next call
            fin->line++;
            fin->position = 0;
            break;
        }

        // If we've reached the end of the stored chunk row, advance to next stored row
        // so subsequent calls continue reading the logical next part.
        if (fin->position >= MAX_FILE_WIDTH) {
            fin->line++;
            fin->position = 0;
            break; // return a partial "fgets"-style chunk
        }
    }

    output[out_i] = '\0';
    return output;
}

bool seof(sfile* fin) {
    if (fin == NULL) return true;
    return (fin->line >= fin->length);
}

// Formatted print to simulated file (analogous to fprintf)
int sfprintf(sfile* fout, const char* format, ...) {
    if (fout == NULL || fout->length >= MAX_FILE_LENGTH) {
        return -1;
    }

    va_list args;
    va_start(args, format);
    int result = vsnprintf(fout->contents[fout->length], MAX_FILE_WIDTH, format, args);
    va_end(args);

    if (result > 0) {
        fout->length++;
    }

    return result;
}

#endif
